include: package:very_good_analysis/analysis_options.yaml

linter:

  rules:
    lines_longer_than_80_chars: false
    omit_local_variable_types: false
    sort_constructors_first: false
    sort_unnamed_constructors_first: false
    prefer_if_elements_to_conditional_expressions: false
    avoid_bool_literals_in_conditional_expressions: false
    sort_pub_dependencies: false
