name: use_template
description: A package to allow users use flutter & dart templates.
version: 1.0.0
# homepage: https://www.example.com
environment:
  sdk: '>=2.17.1 <3.0.0'

dependencies:
  dcli: ^1.31.1

dev_dependencies:
  test: ^1.16.0
  very_good_analysis: ^3.0.0

